backend:
  name: github
  repo: Jozef-Virag/restaurant-admin
  branch: master
  base_url: https://restaurant-admin-beryl.vercel.app
  auth_endpoint: /api/auth

media_folder: "public/uploads"   # kde sa ukladajú obrázky v projekte
public_folder: "/uploads"        # cesta, ktorú bude používať web

collections:
  - name: "menu"
    label: "Týždenné menu"
    folder: "src/content/menu"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - { name: "title", label: "Názov jedla", widget: "string" }
      - { name: "price", label: "Cena", widget: "string" }
      - { name: "description", label: "Popis", widget: "text" }
      - { name: "day", label: "Deň", widget: "select", options: ["Pondelok", "Utorok", "Streda", "Štvrtok", "Piatok"] }
